# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.synced_folder "c:/src", "/home/vagrant/src", create:true

  config.vm.provider "virtualbox" do |vb|
	  #vb.gui = true
	  vb.cpus = 2
	  vb.memory = "8196"

	  vb.customize ["modifyvm", :id, "--vram", "128"]
	  #vb.customize ["modifyvm", :id, "--monitorcount", "2"]
  end

  config.vm.provision "ansible_local" do |ansible|
	  ansible.playbook = "playbook.yml"
  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
